name: r-environment
channels:
  - conda-forge
dependencies:
  - r-base=4.3
  - r-tidyverse
  - r-fbasics
  - r-corrplot
  - r-psych
  - r-glmnet
  - r-glmnetutils
  - r-grf
  - r-rpart
  - r-rpart.plot
  - r-randomforest
  - r-rlang
  - r-readr
  - r-devtools
  - r-reshape2
  - r-caret
  - r-plotmo
  - r-randomfieldsutils
  - r-rms
  - r-hdm
  - r-aer
  - r-lmtest
  - r-dplyr
  - r-sandwich
  - r-diagrammer
  - r-neuralnet
  - r-ISLR2
  - r-zeallot
  - r-nycflights13